### ISSUE TITLE
ievms+iectrl compatibility?

### ISSUE THREAD

**Issue by zamber** [conceptsandtraining/modernie_selenium#6]
Hi,

I'm regularly using ievms and iectrl for manual testing. Wouldn't it be easier to manage the images with these projects instead of provisioning from vanilla modern.ie VMs?

IMHO there are two major advantages:
1. Bandwidth and disk space conservation https://github.com/xdissent/ievms#bandwidth-requirements
2. iectrl allows for painless reinstalling and rearming of vms:

![screen shot 2014-10-15 at 13 48 19](https://cloud.githubusercontent.com/assets/557066/4644866/4cb83598-5461-11e4-88dd-df8c4eba44df.png)

**Comment by niksy** [comment]
Sorry for "opening" closed issue, but this seems like an excellent idea, there is even a Selenium standalone NPM package runner which can be used to automate a lot of the stuff this script does (https://github.com/vvo/selenium-standalone).
